* Inbox

** DONE Prova Português
CLOSED: [2021-11-03 Wed 10:13] DEADLINE: <2021-11-03 Wed>
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-11-03 Wed 10:13]
:END:
Proposta
de Trabalho – Nota A (até 4 pontos)

A
partir das reflexões realizadas em aula e, também, de sua experiência pessoal,
você deverá produzir um texto, sem reescrever os textos-base, ou seja, com
autoria, sobre o seguinte tema: “Se eu fosse eu”.


Nº
de linhas: mínimo de 10
Tipo textual: crônica ou dissertação
Aspectos a serem observados na avaliação: adequação à norma culta da língua, não tangenciamento (isto é, obediência ao tema), coesão, coerência etc.
Prazo de entrega: 21/06/2021


Se eu fosse eu, de Clarice Lispector


 “Quando não
sei onde guardei um papel importante e a procura se revela inútil, pergunto-me:
se eu fosse eu e tivesse um papel importante para guardar, que lugar
escolheria? Às vezes dá certo. Mas muitas vezes fico tão pressionada pela frase
“se eu fosse eu”, que a procura do papel se torna secundária, e começo a
pensar. Diria melhor, sentir. E não me sinto bem. Experimente: se você fosse
você, como seria e o que faria? Logo de início se sente um constrangimento: a
mentira em que nos acomodamos acabou de ser levemente locomovida do lugar onde
se acomodara. No entanto já li biografias de pessoas que de repente passavam a
ser elas mesmas, e mudavam inteiramente de vida. Acho que se eu fosse realmente
eu, os amigos não me cumprimentariam na rua porque até minha fisionomia teria
mudado. Como? Não sei.


Metade das coisas que eu faria se eu fosse eu, não
posso contar. Acho, por exemplo, que por um certo motivo eu terminaria presa na
cadeia. E se eu fosse eu daria tudo o que é meu, e confiaria o futuro ao
futuro. “Se eu fosse eu” parece representar o nosso maior perigo de viver,
parece a entrada nova no desconhecido. No entanto tenho a intuição de que,
passadas as primeiras chamadas loucuras da festa que seria, teríamos enfim a
experiência do mundo. Bem sei, experimentaríamos enfim em pleno a dor do mundo.
E a nossa dor, aquela que aprendemos a não sentir. Mas também seríamos por
vezes tomados de um êxtase de alegria pura e legítima que mal posso adivinhar.
Não, acho que já estou de algum modo adivinhando porque me senti sorrindo e
também senti uma espécie de pudor que se tem diante do que é grande demais.”

** DONE Atividade Física e Imunidade
CLOSED: [2021-11-03 Wed 10:14] DEADLINE: <2021-11-03 Wed>
:LOGBOOK:
- State "DONE"       from "NEXT"       [2021-11-03 Wed 10:14]
:END:

*** Active

** TODO 
  [2022-03-04 Fri 00:00]

** TODO Kill r people
  [2022-06-10 Fri 16:45]
  [[file:~/.emacs.d/init.el::global-set-key (kbd "C-c c") 'org-capture]]

** TODO Finish Setting Up Org-Agenda
  [2022-06-10 Fri 16:47]
  [[file:~/Documentos/Org/refile.org][file:~/Documentos/Org/refile.org]]

** TODO Finish Setting Up Org-Agenda
  [2022-06-10 Fri 16:48]
  [[file:~/Documentos/Org/refile.org][file:~/Documentos/Org/refile.org]]

** TODO Eu perguntei a deus do céu
  [2022-06-10 Fri 22:25]

* Backlog
